### ISSUE TITLE
Use Cete with docker-compose

### ISSUE THREAD

**Issue by aniket-bhange** [mosuka/cete#55]
I tried to launch cete with docker-compose file.
Tried multiple solutions for it but every time, I  run `docker-compose up` it gives port error or permission denied error for creating folder for external directory.
I also tried to add volumes instead of direct directory path still the same.
I am using Mac M1

``` yaml
version:  '3.9'
services: 
    node_1:
      platform: linux/amd64
      image: mosuka/cete:latest
      network_mode: host
      # command: "start --id=node_1 --raft-address=:7000 --grpc-address=:9000 --http-address=:8000"
      ports:
        - 2000:7000
        - 8000:8000
        - 9000:9000
      volumes:
        - data:/tmp/cete/data/node_1:delegated
      environment:
        - CETE_ID=node_1
        - CETE_DATA_DIRECTORY=node_1
        - CETE_RAFT_ADDRESS=7000
        - CETE_GRPC_ADDRESS=9000
        - CETE_HTTP_ADDRESS=8000
```
